name: tests
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Turn on 'editable' mode
        run: |
          pipenv install -e .
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk xvfb
      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x16 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
      - name: Test with pytest
        run: |
          pipenv install pytest
          pipenv --venv
          pipenv run python -m pytest